---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-home-pod
spec:
  containers:
    - name: postgres-home-container
      image: docker.io/library/postgres:18.1
      ports:
        - containerPort: 5432
          hostPort: 5432
      envFrom:
        - secretRef:
            name: postgres-home-secret
      volumeMounts:
        - mountPath: /var/lib/postgresql
          name: postgres-home-data-volume
  volumes:
    - name: postgres-home-data-volume
      persistentVolumeClaim:
        claimName: postgres-home-data-volume-claim
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-home-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-home-data-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
