---
name: Pull request pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    name: Detect changed paths
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      maven: ${{ steps.filter.outputs.maven }}
      frontend: ${{ steps.filter.outputs.frontend }}
      workflow: ${{ steps.filter.outputs.workflow }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - id: filter
        uses: https://github.com/dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**'
            maven:
              - 'maven/**'
            frontend:
              - 'frontend/**'
            workflow:
              - '.forgejo/workflows/pull-request.yaml'
  build-maven-container:
    needs: changes
    if: ${{ needs.changes.outputs.workflow == 'true' || needs.changes.outputs.backend == 'true' || needs.changes.outputs.maven == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: tcp://${{ vars.SERVER_DOMAIN }}:2375
      - name: Login to gitea container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.SERVER_DOMAIN }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:maven"
          push: true
          tags: ${{ vars.SERVER_DOMAIN }}/${{ github.repository }}-maven:latest,
  run-backend-tests:
    needs: [ changes, build-maven-container ]
    if: ${{ needs.changes.outputs.workflow == 'true' || needs.changes.outputs.backend == 'true' || needs.changes.outputs.maven == 'true' }}
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.SERVER_DOMAIN }}/${{ github.repository }}-maven:latest
    steps:
      - name: Check out repository code
        run: git clone -b ${{ forgejo.head_ref }} --single-branch --depth 1 ${{ forgejo.server_url }}/${{ forgejo.repository }}.git
      - name: Run tests
        run: |
          cd home/backend
          mvn clean verify
  run-frontend-tests:
    needs: changes
    if: ${{ needs.changes.outputs.workflow == 'true' || needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    container: docker.io/library/node:24.13.0-slim
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      - name: Check code formatting
        working-directory: frontend
        run: npm run biome-ci
      - name: Check feature sliced design architecture
        working-directory: frontend
        run: npm run steiger
      - name: Run tests
        working-directory: frontend
        run: npm run test
  check-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Obtain next version
        uses: ${{ forgejo.server_url }}/phaib/simple-semantic-release@1.2.1
        with:
          create-release: false
